env:
  browser: true
  es2021: true
extends:
  - google
  - prettier
plugins:
  - 'svelte'
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  indent: ['error', 2, {'SwitchCase': 1, 'CallExpression': {'arguments': 1}}]
  valid-jsdoc: 'off'
  require-jsdoc: 'off'
  camelcase: 'error'
  no-console:
    [
      'error',
      {'allow': ['warn', 'group', 'groupEnd', 'error', 'groupCollapsed']},
    ]
