env:
  browser: true
  es2021: true
extends:
    - google
    - prettier
plugins:
    - 'svelte3'
overrides:
    - files: ['*.svelte']
      processor: 'svelte3/svelte3'
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  indent: [2,2]
  valid-jsdoc: "off"
  require-jsdoc: "off"
  camelcase: "off"
