name: Run CD
on:
  workflow_dispatch:
  # Allows external webhook trigger
  repository_dispatch:
    types:
      - webhook
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install

      - name: Run formatter and tests
        run: |
          npm run format_check
          npm run lint
          npm run test

      - name: Deploy production on cloudflare
        env: # Set the secret as an input
          WEBHOOK: ${{ secrets.CLOUDFLARE_WEBHOOK }}
        run: |
          curl -X POST "$WEBHOOK"
